import { useEffect, useState } from "react";
import type React from "react";
import { Activity, AlertTriangle, BarChart3, CalendarDays, ChevronRight, ClipboardCheck, FileText, Gauge, LayoutDashboard, LogOut, Menu, PackageSearch, Search, Settings, ShieldCheck, UserPlus, Wrench, X } from "lucide-react";
import { supabase } from "./lib/supabase";

type Section={id:string;label:string;icon:React.ComponentType<{size?:number}>};
const sections:Section[]=[
{id:"dashboard",label:"Dashboard",icon:LayoutDashboard},{id:"assets",label:"Assets",icon:PackageSearch},{id:"reliability",label:"Reliability",icon:Activity},{id:"maintenance",label:"Maintenance",icon:Wrench},{id:"visits",label:"Site Visits",icon:ClipboardCheck},{id:"calendar",label:"Calendar",icon:CalendarDays},{id:"technical",label:"Technical Library",icon:Gauge},{id:"documents",label:"Documents",icon:FileText},{id:"maximo",label:"Maximo",icon:ShieldCheck}
];
type Site={id:string;code:string;name:string}; type Asset={id:string;asset_tag:string;name:string;asset_class:string|null;criticality:number|null;status:string};

export default function App(){
 const [session,setSession]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{ if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>data.subscription.unsubscribe(); },[]);
 if(loading) return <div className="center"><div className="loader"/><span>Loading Reliability Platform…</span></div>;
 if(!supabase) return <div className="center"><h2>Configuration needed</h2><p>Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in the app environment.</p></div>;
 if(!session) return <AuthScreen/>;
 return <AuthenticatedApp session={session}/>;
}

function AuthScreen(){
 const [mode,setMode]=useState<"signin"|"signup">("signin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage(""); if(mode==="signin"){const r=await supabase!.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message)}else{const r=await supabase!.auth.signUp({email,password,options:{data:{display_name:name}}});if(r.error)setError(r.error.message);else setMessage(r.data.session?"Account created.":"Account created. Check your email if confirmation is required.")}setBusy(false)}
 return <div className="auth-shell"><div className="auth-card"><div className="auth-brand"><div className="mark">R</div><div><strong>Reliability</strong><span>Engineering Platform</span></div></div><p className="eyebrow">SECURE WORKSPACE</p><h1>{mode==="signin"?"Welcome back":"Create your account"}</h1><p className="muted">{mode==="signin"?"Sign in to access your reliability workspace.":"Create a development account to begin."}</p><form onSubmit={submit}>{mode==="signup"&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="••••••••"/></label>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}<button className="primary full" disabled={busy}>{busy?"Working…":mode==="signin"?"Sign in":"Create account"}</button></form><button className="switch" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setError("");setMessage("")}}>{mode==="signin"?<><UserPlus size={15}/> Create an account</>:<>Already have an account? Sign in</>}</button></div></div>
}

function AuthenticatedApp({session}:{session:any}){
 const [active,setActive]=useState("dashboard"); const [open,setOpen]=useState(false); const current=sections.find(s=>s.id===active)!;
 return <div className="app"><aside className={open?"sidebar open":"sidebar"}><div className="brand"><div className="mark">R</div><div><strong>Reliability</strong><span>Engineering Platform</span></div><button className="icon mobile-close" onClick={()=>setOpen(false)}><X/></button></div><nav>{sections.map(s=>{const I=s.icon;return <button className={active===s.id?"nav active":"nav"} key={s.id} onClick={()=>{setActive(s.id);setOpen(false)}}><I size={19}/><span>{s.label}</span></button>})}</nav><div className="sidebar-bottom"><button className="nav" onClick={()=>supabase!.auth.signOut()}><LogOut size={19}/><span>Sign out</span></button><div className="environment"><span className="dot"/>Connected workspace</div></div></aside><main className="main"><header><button className="icon menu-btn" onClick={()=>setOpen(true)}><Menu/></button><div className="crumb"><span>Reliability Platform</span><ChevronRight size={16}/><b>{current.label}</b></div><div className="header-actions"><button className="icon"><Search/></button><div className="avatar">{(session.user.email||"RE").slice(0,2).toUpperCase()}</div></div></header><div className="content">{active==="dashboard"?<Dashboard/>:<SectionPage section={current}/>}</div></main></div>
}

function Dashboard(){
 const [sites,setSites]=useState<Site[]>([]); const [assets,setAssets]=useState<Asset[]>([]); const [error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{const s=await supabase!.from("sites").select("id,code,name").order("name");if(s.error){if(live)setError(s.error.message);return}const a=await supabase!.from("assets").select("id,asset_tag,name,asset_class,criticality,status").order("name").limit(50);if(live){setSites(s.data||[]);setAssets(a.data||[]);if(a.error)setError(a.error.message)}})();return()=>{live=false}},[]);
 return <><div className="hero"><div><p className="eyebrow">RELIABILITY OVERVIEW</p><h1>Good morning.</h1><p className="muted">Connected to your Supabase reliability workspace.</p></div><button className="primary"><span>+</span> Log activity</button></div>{error&&<div className="notice error wide">{error}</div>}<div className="grid metrics"><div className="metric"><div className="metric-top"><span>Sites</span><ShieldCheck size={17}/></div><strong>{sites.length}</strong><small>Sites you can access</small></div><div className="metric"><div className="metric-top"><span>Assets</span><PackageSearch size={17}/></div><strong>{assets.length}</strong><small>Assets visible in workspace</small></div><div className="metric"><div className="metric-top"><span>Critical assets</span><AlertTriangle size={17}/></div><strong>{assets.filter(a=>(a.criticality||0)>=4).length}</strong><small>Criticality 4–5</small></div><div className="metric"><div className="metric-top"><span>Workspace</span><BarChart3 size={17}/></div><strong>Live</strong><small>Supabase connected</small></div></div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Sites</h2><p>Authorized operating locations</p></div></div>{sites.length?<div className="list">{sites.map(s=><Item key={s.id} title={s.name} detail={s.code} tag="Active"/></div>:<Empty text="No site access has been assigned to this account yet."/>}</section><section className="panel"><div className="panel-head"><div><h2>Assets</h2><p>Current asset records</p></div></div>{assets.length?<div className="list">{assets.slice(0,6).map(a=><Item key={a.id} title={a.name} detail={a.asset_tag+(a.asset_class?" · "+a.asset_class:"")} tag={a.status}/>)}</div>:<Empty text="No assets are visible yet. Site membership controls access."/>}</section></div><section className="panel quick"><div className="panel-head"><div><h2>Next build layer</h2><p>The live application will expand from this connected foundation.</p></div></div><div className="quick-grid"><Quick title="Asset hierarchy" text="Site → area → line → machine → subsystem → component"/><Quick title="Failure management" text="Failures, modes, causes, downtime and RCA"/><Quick title="Technical library" text="Specs, lubricants, documents and source references"/><Quick title="Maximo bridge" text="CSV/Excel import first, API integration later"/></div></section></>
}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Item({title,detail,tag}:{title:string;detail:string;tag:string}){return <div className="list-row"><div className="row-icon"><Activity size={17}/></div><div className="row-copy"><b>{title}</b><span>{detail}</span></div><span className="tag">{tag}</span></div>}
function Quick({title,text}:{title:string;text:string}){return <button className="quick-card"><b>{title}</b><span>{text}</span><ChevronRight size={17}/></button>}
function SectionPage({section}:{section:Section}){const I=section.icon;return <div className="empty-page"><div className="page-icon"><I size={28}/></div><p className="eyebrow">MODULE</p><h1>{section.label}</h1><p className="muted">The navigation is live. This module will be connected to its Supabase records and workflows as we build the platform layer by layer.</p><div className="panel roadmap"><h2>Connected foundation</h2><p>Authentication is live, the database is already structured, and access is controlled by site membership. The next records will plug into this shell without rebuilding the application.</p></div></div>}
