import { useEffect, useState } from "react";
import { FileSpreadsheet } from "lucide-react";
import * as XLSX from "xlsx";
import { supabase } from "./lib/supabase";

export default function ImportCenter(){
 const [sites,setSites]=useState<any[]>([]);const [rows,setRows]=useState<any[]>([]);const [headers,setHeaders]=useState<string[]>([]);const [mapping,setMapping]=useState<Record<string,string>>({asset_tag:"",name:"",site:"",asset_class:"",manufacturer:"",model:"",serial_number:"",criticality:"",status:"",maximo_asset_id:"",description:""});const [fileName,setFileName]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 useEffect(()=>{void supabase!.from("sites").select("id,code,name").order("name").then(r=>setSites(r.data||[]))},[]);
 async function readFile(file:File){setFileName(file.name);setError("");setMessage("");try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Record<string,any>>(ws,{defval:""});const h=parsed.length?Object.keys(parsed[0]):[];setRows(parsed.slice(0,1000));setHeaders(h);const guess=(terms:string[])=>h.find(x=>terms.some(t=>x.toLowerCase().trim()===t||x.toLowerCase().includes(t)))||"";setMapping({asset_tag:guess(["asset tag","asset #","assetnum","asset number"]),name:guess(["name","description"]),site:guess(["site","site code","site id"]),asset_class:guess(["asset class","class","equipment class"]),manufacturer:guess(["manufacturer","mfr"]),model:guess(["model"]),serial_number:guess(["serial"]),criticality:guess(["criticality"]),status:guess(["status"]),maximo_asset_id:guess(["maximo asset","assetnum"]),description:guess(["description"])})}catch(e){setError(e instanceof Error?e.message:"Could not read the spreadsheet.")}}
 async function importRows(){setBusy(true);setError("");let imported=0,skipped=0;for(const row of rows){const sv=String(row[mapping.site]||"").trim();const site=sites.find(s=>s.id===sv||s.code.toLowerCase()===sv.toLowerCase()||s.name.toLowerCase()===sv.toLowerCase());const tag=String(row[mapping.asset_tag]||"").trim();const name=String(row[mapping.name]||"").trim();if(!site||!tag||!name){skipped++;continue}const status=(String(row[mapping.status]||"active").trim().toLowerCase()||"active");const payload={site_id:site.id,asset_tag:tag,name,asset_class:String(row[mapping.asset_class]||"").trim()||null,manufacturer:String(row[mapping.manufacturer]||"").trim()||null,model:String(row[mapping.model]||"").trim()||null,serial_number:String(row[mapping.serial_number]||"").trim()||null,criticality:Number(row[mapping.criticality])||null,status:["active","inactive","retired"].includes(status)?status:"active",maximo_asset_id:String(row[mapping.maximo_asset_id]||"").trim()||null,description:String(row[mapping.description]||"").trim()||null};const r=await supabase!.from("assets").upsert(payload,{onConflict:"site_id,asset_tag"});if(r.error)skipped++;else imported++}setMessage("Imported "+imported+" asset"+(imported===1?"":"s")+"."+ (skipped?" "+skipped+" row"+(skipped===1?"":"s")+" skipped.":""));setBusy(false)}
 return <div><div className="hero"><div><p className="eyebrow">DATA IMPORT</p><h1>Import Center</h1><p className="muted">Preview your Excel or CSV equipment list, map columns, then write it to the shared asset database.</p></div></div>{error&&<div className="notice error wide">{error}</div>}{message&&<div className="notice wide">{message}</div>}<section className="panel import-panel"><label className="dropzone"><FileSpreadsheet size={28}/><b>{fileName||"Choose an Excel or CSV file"}</b><span>.xlsx, .xls, or .csv · first worksheet · up to 1,000 rows</span><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void readFile(f)}}/></label>{headers.length>0&&<><div className="import-meta">{rows.length} rows loaded</div><div className="mapping-grid">{Object.entries(mapping).map(([key,value])=><label key={key}>{key.replaceAll("_"," ")}<select value={value} onChange={e=>setMapping(m=>({...m,[key]:e.target.value}))}><option value="">— not mapped —</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><div className="preview-table"><div className="preview-head">{headers.slice(0,7).map(h=><span key={h}>{h}</span>)}</div>{rows.slice(0,5).map((r,i)=><div className="preview-row" key={i}>{headers.slice(0,7).map(h=><span key={h}>{String(r[h]??"")}</span>)}</div>)}</div><button className="primary" disabled={busy} onClick={importRows}>{busy?"Importing…":"Import "+rows.length+" rows"}</button></>}</section></div>
}