import { useEffect, useState } from "react";
import { ClipboardCheck, FileText, Plus } from "lucide-react";
import { supabase } from "./lib/supabase";

export function VisitsPage(){
 const [sites,setSites]=useState<any[]>([]);const [visits,setVisits]=useState<any[]>([]);const [form,setForm]=useState({site_id:"",visit_date:new Date().toISOString().slice(0,10),purpose:"",summary:""});const [error,setError]=useState("");
 async function load(){const auth=await supabase!.auth.getUser();if(auth.error||!auth.data.user){setError(auth.error?.message||"Your session could not be confirmed.");return}const [s,v]=await Promise.all([supabase!.from("sites").select("id,code,name").order("name"),supabase!.from("site_visits").select("id,site_id,visit_date,purpose,summary,created_at").eq("created_by",auth.data.user.id).order("visit_date",{ascending:false})]);if(s.error)setError(s.error.message);else setSites(s.data||[]);if(v.error)setError(v.error.message);else setVisits(v.data||[])}
 useEffect(()=>{void load()},[]);
 async function add(){const u=await supabase!.auth.getUser();const r=await supabase!.from("site_visits").insert({...form,created_by:u.data.user?.id}).select().single();if(r.error)setError(r.error.message);else{setForm({...form,purpose:"",summary:""});await load()}}
 return <div><div className="hero"><div><p className="eyebrow">PERSONAL WORKSPACE</p><h1>My Site Visits</h1><p className="muted">Your visit log is private to your account.</p></div></div>{error&&<div className="notice error wide">{error}</div>}<div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Log a visit</h2><p>Linked to a shared site, but visible only to you.</p></div></div><div className="form-grid"><label>Site<select value={form.site_id} onChange={e=>setForm({...form,site_id:e.target.value})}><option value="">Select site…</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Date<input type="date" value={form.visit_date} onChange={e=>setForm({...form,visit_date:e.target.value})}/></label><label className="span-2">Purpose<input value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></label><label className="span-2">Summary<textarea rows={6} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label></div><button className="primary" disabled={!form.site_id} onClick={add}><Plus size={16}/> Save visit</button></section><section className="panel"><div className="panel-head"><div><h2>My visit history</h2><p>Private records</p></div></div>{visits.length?<div className="list">{visits.map(v=><div className="list-row" key={v.id}><div className="row-icon"><ClipboardCheck size={17}/></div><div className="row-copy"><b>{sites.find(s=>s.id===v.site_id)?.name||"Site"}</b><span>{v.visit_date} · {v.purpose||"Visit"}{v.summary?" · "+v.summary:""}</span></div></div>)}</div>:<div className="empty">No visits logged yet.</div>}</section></div></div>
}

export function NotesPage(){
 const [notes,setNotes]=useState<any[]>([]);const [sites,setSites]=useState<any[]>([]);const [form,setForm]=useState({site_id:"",title:"",body:"",note_type:"engineering"});const [error,setError]=useState("");
 async function load(){const [n,s]=await Promise.all([supabase!.from("notes").select("id,site_id,title,body,note_type,created_at").order("created_at",{ascending:false}),supabase!.from("sites").select("id,code,name").order("name")]);if(n.error)setError(n.error.message);else setNotes(n.data||[]);if(s.error)setError(s.error.message);else setSites(s.data||[])}
 useEffect(()=>{void load()},[]);
 async function add(){const u=await supabase!.auth.getUser();const r=await supabase!.from("notes").insert({...form,site_id:form.site_id||null,author_id:u.data.user?.id}).select().single();if(r.error)setError(r.error.message);else{setForm({site_id:"",title:"",body:"",note_type:"engineering"});await load()}}
 return <div><div className="hero"><div><p className="eyebrow">PERSONAL WORKSPACE</p><h1>My Notes</h1><p className="muted">Private working notes. Shared asset data stays separate.</p></div></div>{error&&<div className="notice error wide">{error}</div>}<div className="two-col"><section className="panel"><div className="panel-head"><div><h2>New note</h2><p>Only your account can read it.</p></div></div><div className="form-grid"><label>Site<select value={form.site_id} onChange={e=>setForm({...form,site_id:e.target.value})}><option value="">No site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Type<select value={form.note_type} onChange={e=>setForm({...form,note_type:e.target.value})}><option value="engineering">Engineering</option><option value="site_visit">Site visit</option><option value="maintenance">Maintenance</option><option value="general">General</option><option value="rCA">RCA</option></select></label><label className="span-2">Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="span-2">Note<textarea rows={7} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label></div><button className="primary" disabled={!form.body.trim()} onClick={add}><Plus size={16}/> Save note</button></section><section className="panel"><div className="panel-head"><div><h2>My notes</h2><p>Private records</p></div></div>{notes.length?<div className="list">{notes.map(n=><div className="list-row" key={n.id}><div className="row-icon"><FileText size={17}/></div><div className="row-copy"><b>{n.title||"Untitled note"}</b><span>{new Date(n.created_at).toLocaleString()} · {n.body}</span></div><span className="tag">{n.note_type}</span></div>)}</div>:<div className="empty">No notes yet.</div>}</section></div></div>
}
