import { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { supabase } from "./lib/supabase";

export default function SitesPage(){
 const [sites,setSites]=useState<any[]>([]);
 const [form,setForm]=useState({code:"",name:"",timezone:"America/Chicago",description:""});
 const [error,setError]=useState("");
 const [message,setMessage]=useState("");
 async function load(){const r=await supabase!.from("sites").select("id,code,name,description,timezone,active").order("name");if(r.error)setError(r.error.message);else setSites(r.data||[])}
 useEffect(()=>{void load()},[]);
 async function add(){setError("");setMessage("");const u=await supabase!.auth.getUser();const r=await supabase!.from("sites").insert({code:form.code.trim(),name:form.name.trim(),timezone:form.timezone.trim(),description:form.description.trim()||null}).select().single();if(r.error){setError(r.error.message);return}await supabase!.from("site_memberships").insert({user_id:u.data.user?.id,site_id:r.data.id});setMessage("Site created and added to your access.");setForm({code:"",name:"",timezone:"America/Chicago",description:""});await load()}
 return <div><div className="hero"><div><p className="eyebrow">SHARED WORKSPACE</p><h1>Sites</h1><p className="muted">Sites are shared. Authorized users see the same equipment and photos within each site.</p></div></div>{error&&<div className="notice error wide">{error}</div>}{message&&<div className="notice wide">{message}</div>}<div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Add a site</h2><p>Workspace administrators can create operating locations.</p></div></div><div className="form-grid"><label>Site code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="SITE-01"/></label><label>Site name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Plant name"/></label><label>Time zone<input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})} placeholder="America/Chicago"/></label><label className="span-2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3}/></label></div><button className="primary" disabled={!form.code.trim()||!form.name.trim()} onClick={add}><Plus size={16}/> Create site</button></section><section className="panel"><div className="panel-head"><div><h2>Accessible sites</h2><p>Shared site records</p></div></div>{sites.length?<div className="list">{sites.map(s=><div className="list-row" key={s.id}><div className="row-copy"><b>{s.name}</b><span>{s.code} · {s.timezone||"No timezone"}</span></div><span className="tag">Shared</span></div>)}</div>:<div className="empty">No sites yet.</div>}</section></div></div>
}