create or replace function public.is_site_member(p_site_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.site_memberships sm where sm.site_id=p_site_id and sm.user_id=auth.uid()); $$;
create or replace function public.asset_site_id(p_asset_id uuid) returns uuid language sql stable security definer set search_path=public as $$ select s.id from public.sites s join public.areas a on a.site_id=s.id join public.production_lines pl on pl.area_id=a.id join public.assets x on x.production_line_id=pl.id where x.id=p_asset_id limit 1; $$;
create policy profiles_self on public.profiles for all to authenticated using (id=auth.uid()) with check (id=auth.uid());
create policy roles_authenticated_read on public.roles for select to authenticated using (true);
create policy user_roles_self on public.user_roles for select to authenticated using (user_id=auth.uid());
create policy sites_member_read on public.sites for select to authenticated using (public.is_site_member(id));
create policy site_memberships_self on public.site_memberships for select to authenticated using (user_id=auth.uid());
create policy areas_member_read on public.areas for select to authenticated using (public.is_site_member(site_id));
create policy lines_member_read on public.production_lines for select to authenticated using (exists(select 1 from public.areas a where a.id=area_id and public.is_site_member(a.site_id)));
create policy assets_member_read on public.assets for select to authenticated using (public.is_site_member(public.asset_site_id(id)));
create policy components_member_read on public.asset_components for select to authenticated using (public.is_site_member(public.asset_site_id(asset_id)));
create policy failures_member_read on public.failure_events for select to authenticated using (public.is_site_member(public.asset_site_id(asset_id)));
create policy projects_member_read on public.reliability_projects for select to authenticated using (site_id is null or public.is_site_member(site_id));
create policy actions_member_read on public.corrective_actions for select to authenticated using (exists(select 1 from public.reliability_projects p where p.id=project_id and (p.site_id is null or public.is_site_member(p.site_id))));
create policy visits_member_read on public.site_visits for select to authenticated using (public.is_site_member(site_id));
create policy notes_member_read on public.notes for select to authenticated using (site_id is null or public.is_site_member(site_id) or (asset_id is not null and public.is_site_member(public.asset_site_id(asset_id))));
create policy documents_member_read on public.documents for select to authenticated using (site_id is null or public.is_site_member(site_id) or (asset_id is not null and public.is_site_member(public.asset_site_id(asset_id))));
create policy document_versions_member_read on public.document_versions for select to authenticated using (exists(select 1 from public.documents d where d.id=document_id and (d.site_id is null or public.is_site_member(d.site_id))));
create policy lubricants_authenticated_read on public.lubricants for select to authenticated using (true);
create policy specs_member_read on public.technical_specifications for select to authenticated using ((asset_id is not null and public.is_site_member(public.asset_site_id(asset_id))) or (component_id is not null and public.is_site_member(public.asset_site_id((select c.asset_id from public.asset_components c where c.id=component_id)))));
create policy maximo_assets_member_read on public.maximo_assets for select to authenticated using (site_id is null or public.is_site_member(site_id));
create policy maximo_wo_member_read on public.maximo_work_orders for select to authenticated using (site_id is null or public.is_site_member(site_id));
create policy kpi_definitions_member_read on public.kpi_definitions for select to authenticated using (site_id is null or public.is_site_member(site_id));
create policy kpi_values_member_read on public.kpi_values for select to authenticated using (exists(select 1 from public.kpi_definitions k where k.id=kpi_id and (k.site_id is null or public.is_site_member(k.site_id))));
