create table public.lubricants (id uuid primary key default gen_random_uuid(), manufacturer text, product_name text not null, lubricant_type text, viscosity_grade text, base_oil text, nlgi_grade text, operating_temperature_min_c numeric, operating_temperature_max_c numeric, notes text, source_document_id uuid references public.documents(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.technical_specifications (id uuid primary key default gen_random_uuid(), asset_id uuid references public.assets(id) on delete cascade, component_id uuid references public.asset_components(id) on delete cascade, specification_name text not null, specification_value text not null, unit text, source_type text not null check(source_type in ('manufacturer','engineering_reference','company_standard','user_entered')), source_document_id uuid references public.documents(id) on delete set null, source_page text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(asset_id is not null or component_id is not null));
create table public.maximo_assets (id uuid primary key default gen_random_uuid(), maximo_asset_id text not null unique, site_id uuid references public.sites(id) on delete set null, asset_tag text, description text, status text, location text, parent_asset_id text, raw_data jsonb, imported_at timestamptz not null default now());
create table public.maximo_work_orders (id uuid primary key default gen_random_uuid(), maximo_work_order_id text not null unique, maximo_asset_id text, site_id uuid references public.sites(id) on delete set null, description text, status text, work_type text, priority integer, reported_date timestamptz, target_start timestamptz, actual_start timestamptz, actual_finish timestamptz, raw_data jsonb, imported_at timestamptz not null default now());
create table public.kpi_definitions (id uuid primary key default gen_random_uuid(), site_id uuid references public.sites(id) on delete cascade, name text not null, code text not null, description text, unit text, calculation_definition jsonb, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(site_id,code));
create table public.kpi_values (id uuid primary key default gen_random_uuid(), kpi_id uuid not null references public.kpi_definitions(id) on delete cascade, asset_id uuid references public.assets(id) on delete set null, period_start date not null, period_end date not null, value numeric, target numeric, source text, created_at timestamptz not null default now(), unique(kpi_id,asset_id,period_start,period_end));
create index assets_parent_asset_id_idx on public.assets(parent_asset_id);
create index failure_events_asset_id_occurred_at_idx on public.failure_events(asset_id,occurred_at desc);
create index notes_asset_id_created_at_idx on public.notes(asset_id,created_at desc);
create index documents_asset_id_idx on public.documents(asset_id);
create index technical_specs_asset_id_idx on public.technical_specifications(asset_id);
create index maximo_work_orders_asset_id_idx on public.maximo_work_orders(maximo_asset_id);
create index kpi_values_kpi_period_idx on public.kpi_values(kpi_id,period_start desc);
insert into public.roles(name,description) values ('admin','Full platform administration'),('engineer','Reliability and engineering access'),('planner','Maintenance planning and scheduling access'),('maintenance','Maintenance execution and technical access'),('viewer','Read-only access') on conflict(name) do nothing;
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.sites enable row level security;
alter table public.site_memberships enable row level security;
alter table public.areas enable row level security;
alter table public.production_lines enable row level security;
alter table public.assets enable row level security;
alter table public.asset_components enable row level security;
alter table public.failure_events enable row level security;
alter table public.reliability_projects enable row level security;
alter table public.corrective_actions enable row level security;
alter table public.site_visits enable row level security;
alter table public.notes enable row level security;
alter table public.documents enable row level security;
alter table public.document_versions enable row level security;
alter table public.lubricants enable row level security;
alter table public.technical_specifications enable row level security;
alter table public.maximo_assets enable row level security;
alter table public.maximo_work_orders enable row level security;
alter table public.kpi_definitions enable row level security;
alter table public.kpi_values enable row level security;
revoke all on all tables in schema public from anon,authenticated;
revoke all on all sequences in schema public from anon,authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
